### ISSUE TITLE
Add Markdown Linter

### ISSUE THREAD

**Issue by jonleung** [hackclub/markcop#1]
As discussed on a call on Friday, September 4th.

**Comment by zachlatta** [comment]
Closing due to lack of specificity. Can you talk about features you want?

**Comment by jonleung** [comment]
I want the linter to catch anything that does not conform to [our Markdown styleguide](https://github.com/hackedu/meta/blob/master/markdown_style_guide.md).

**Comment by zachlatta** [comment]
Can you create a new issue that's a bit more descriptive?

On Sat, Sep 5, 2015 at 8:18 AM, Jonathan Leung notifications@github.com
wrote:

> Reopened #1 https://github.com/hackedu/markcop/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/markcop/issues/1#event-401888510.

## 

Zach Latta
hackEDU | zach@hackedu.us
