### ISSUE TITLE
Add check to see if Markdown conforms to our styleguide

### ISSUE THREAD

**Issue by jonleung** [hackclub/markcop#2]
[Link to styleguide](https://github.com/hackedu/meta/blob/master/markdown_style_guide.md)

**Comment by maxwofford** [comment]
@zachlatta Should these tests be broken into individual files?

**Comment by maxwofford** [comment]
Current plans for things to check:
- [x] Trailing spaces (using `^.+\s$`)
- [x] Incorrectly formatted headings
  - [x] Headings have a space after their `#'s` (using `^\#{1,6}(\w).+$`)
  - [x] Only 6 levels of headings (`^\#{7,}.+$`)
  - [x] Headings don't have closing `#'s` (using `\#[^#]+\#$`)
    ~~[ ] Headers should have leading and trailing newlines~~
- [x] Lines over 80 characters (using `.{80,}`)

EDIT: Moved newlines issue to https://github.com/hackedu/markcop/issues/12

**Comment by maxwofford** [comment]
@zachlatta The current format outputs checks like this. Would love to get your thoughts:

``` md
Checking for trailing whitespace...
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Checking for incorrect headings...
..........................................................
No bad headers!

Checking for long lines...
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Checking for missing links...
...........................................................
No broken links!


5:README.md '#bad title here' is a bad header!
#other logs here in the format line_number:file_name 'line_contents' is a bad header/is over  80 chars
```

**Comment by jonleung** [comment]
@MaxWofford this is awesome!

**Comment by zachlatta** [comment]
What's the status on this? Do we have checks to make sure headers have leading and trailing newlines?

**Comment by maxwofford** [comment]
@zachlatta Not yet. I might break this into a new issue, but for checking newlines around headers I'd like to refactor markcop quite a bit.

**Comment by zachlatta** [comment]
Can you go ahead and break that into a new issue? Since most of the work for this one is done, I'd love to get it closed (especially if getting that last check requires a larger refactor).

**Comment by maxwofford** [comment]
Just  transferred the left-over issue to https://github.com/hackedu/markcop/issues/12
