### ISSUE TITLE
Markop saying there are errors when there are not

### ISSUE THREAD

**Issue by jonleung** [hackclub/markcop#27]
@msw @zachlatta, the tests seem to be marking things that are broken that are not broken.

See hackedu/meta#253

There are the errors that I'm getting from markcop:

```
60:applications/knight_cities_app_fall_15.md '##  Location:' doesn't have a space between the # and the text of the header!
82:applications/knight_cities_app_fall_15.md '##  Contact Details:' doesn't have a space between the # and the text of the header!
33:applications/knight_cities_app_fall_15.md is over 80 chars!
39:applications/knight_cities_app_fall_15.md is over 80 chars!
40:applications/knight_cities_app_fall_15.md is over 80 chars!
51:applications/knight_cities_app_fall_15.md is over 80 chars!
```

This is the file that is supposedly broken but if you look at the errors and compare the files, this is not the case:

https://github.com/hackedu/meta/pull/253/files#diff-098b94b799bdad2d770c43117012c133R60

/cc @MaxWofford @zachlatta

**Comment by maxwofford** [comment]
It was unicode
