### ISSUE TITLE
Tests all the way down...

### ISSUE THREAD

**Issue by maxwofford** [hackclub/markcop#36]
We need tests for MarkCop tests.

**Comment by jonleung** [comment]
Should we still do this?

**Comment by maxwofford** [comment]
@jonleung Yep! It's important we add tests so people can contribute to Markcop without breaking anything

**Comment by zachlatta** [comment]
Agreed that tests are important.

**Comment by selynna** [comment]
@zachlatta @MaxWofford do we still need this

**Comment by maxwofford** [comment]
Closing this because it's been inactive.

**Comment by maxwofford** [comment]
If anyone wants to take point on it feel free to reopen in the future.
