### ISSUE TITLE
Create installer script for use on c9

### ISSUE THREAD

**Issue by maxwofford** [hackclub/markcop#4]

**Comment by zachlatta** [comment]
:thumbsup:

On Fri, Sep 25, 2015 at 5:56 PM, Max Wofford notifications@github.com
wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/markcop/issues/4.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
Closed by #10.
