### ISSUE TITLE
Add dictionary test

### ISSUE THREAD

**Issue by ZucchiniZe** [hackclub/markcop#42]
add a dictionary test so words get spell checked.

**Comment by zachlatta** [comment]
This is a great idea. I love it.

**Comment by maxwofford** [comment]
This is introduced in https://github.com/hackclub/markcop/pull/44. I'm happy to add a check for it, but tests shouldn't fail if it finds a word that isn't correct. There are lots of instances of incorrectly spelled things in our repos that should stay the way they are. 'ex. Lorem ipsum'

**Comment by zachlatta** [comment]
Closed by #50 :-).
