### ISSUE TITLE
Limit file sizes

### ISSUE THREAD

**Issue by maxwofford** [hackclub/markcop#79]
Ensure that gifs are all under 30mb

**Comment by zachlatta** [comment]
Do we have GIFs that are over 30MB? Sounds like an overly permissive limit.

**Comment by maxwofford** [comment]
@zachlatta I'll check the filesizes in our repo and change the limit  in the description.

**Comment by zachlatta** [comment]
Going to go ahead and close this. File size no longer seems like a priority.
